<div class="list-group hidden-xs">
	<a href="/pertanyaan?search=Aqidah" class="list-group-item">Aqidah</a>
	<a href="/pertanyaan?search=Aqiqah" class="list-group-item">Aqiqah</a>
	<a href="/pertanyaan?search=Bid'ah" class="list-group-item">Bid'ah</a>
	<a href="/pertanyaan?search=Do'a" class="list-group-item">Do'a</a>
	<a href="/pertanyaan?search=Dzikir" class="list-group-item">Dzikir</a>
	<a href="/pertanyaan?search=Fiqh" class="list-group-item">Fiqh</a>
	<a href="/pertanyaan?search=Hadas" class="list-group-item">Hadas</a>
	<a href="/pertanyaan?search=Hadith" class="list-group-item">Hadith</a>
	<a href="/pertanyaan?search=Haji" class="list-group-item">Haji</a>
	<a href="/pertanyaan?search=Hukum" class="list-group-item">Hukum</a>
	<a href="/pertanyaan?search=Ibadah" class="list-group-item">Ibadah</a>
	<a href="/pertanyaan?search=Ihsan" class="list-group-item">Ihsan</a>
	<a href="/pertanyaan?search=Iman" class="list-group-item">Iman</a>
	<a href="/pertanyaan?search=Islam" class="list-group-item">Islam</a>
	<a href="/pertanyaan?search=Jenazah" class="list-group-item">Jenazah</a>
	<a href="/pertanyaan?search=Janabah" class="list-group-item">Janabah</a>
	<a href="/pertanyaan?search=Kontemporer" class="list-group-item">Kontemporer</a>
	<a href="/pertanyaan?search=Mayit" class="list-group-item">Mayit</a>
	<a href="/pertanyaan?search=Muamalah" class="list-group-item">Muamalah</a>
	<a href="/pertanyaan?search=Najis" class="list-group-item">Najis</a>
	<a href="/pertanyaan?search=Nikah" class="list-group-item">Nikah</a>
	<a href="/pertanyaan?search=Puasa" class="list-group-item">Puasa</a>
	<a href="/pertanyaan?search=Poligami" class="list-group-item">Poligami</a>
	<a href="/pertanyaan?search=Qurban" class="list-group-item">Qurban</a>
	<a href="/pertanyaan?search=Rujuk" class="list-group-item">Rujuk</a>
	<a href="/pertanyaan?search=Shalat" class="list-group-item">Shalat</a>
	<a href="/pertanyaan?search=Shaum" class="list-group-item">Shaum</a>
	<a href="/pertanyaan?search=Sunnah" class="list-group-item">Sunnah</a>
	<a href="/pertanyaan?search=Talak" class="list-group-item">Talak</a>
	<a href="/pertanyaan?search=Ta'addud" class="list-group-item">Ta'addud</a>
	<a href="/pertanyaan?search=Tauhid" class="list-group-item">Tauhid</a>
	<a href="/pertanyaan?search=Thaharah" class="list-group-item">Thaharah</a>
	<a href="/pertanyaan?search=Umrah" class="list-group-item">Umrah</a>
	<a href="/pertanyaan?search=Waris" class="list-group-item">Waris</a>
	<a href="/pertanyaan?search=Zakat" class="list-group-item">Zakat</a>
</div>
